# Generated by Django 4.1 on 2025-02-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_rename_genre_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="seats_in_row",
            new_name="seat_in_row",
        ),
    ]
