# Generated by Django 4.1 on 2025-02-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_rename_seats_in_row_cinemahall_seat_in_row"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="seat_in_row",
            new_name="seats_in_row",
        ),
    ]
