# Generated by Django 4.1 on 2025-02-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_rename_seat_in_row_cinemahall_seats_in_row"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinemahall",
            old_name="seats_in_row",
            new_name="seats_in_rows",
        ),
    ]
